// src/data/fakePosts.js
const userAvatars = {
  "E&S": "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg",
  "Jake & Mia": "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg",
  "Liam & Ava": "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg",
  "Noah & Emma": "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg",
};

export const fakePosts = [

  // --- E&S Avatar ---
  // https://source.unsplash.com/100x100/?couple,portrait
  // --- Jake & Mia Avatar ---
  // https://source.unsplash.com/100x100/?young,couple
  // --- Liam & Ava Avatar ---
  // https://source.unsplash.com/100x100/?romantic,couple
  // --- Noah & Emma Avatar ---
  // https://source.unsplash.com/100x100/?happy,couple

  
{
        id: 3,
        user: "E&S",
        avatar: userAvatars["E&S"],
        time: "15 minutes ago",
        title: "Coffee & Bookstore Date",
        image: "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg",
        description: "Browsed books and grabbed lattes after.",
        tags: ["Indoor", "Cheap", "Relaxing"],
        likes: 8,
        liked: false,
        seen: false,
    },
    {
        id: 9,
        user: "Jake & Mia",
        avatar: userAvatars["Jake & Mia"],
        time: "1 hour ago",
        title: "Rock Climbing Gym",
        image: "https://images.pexels.com/photos/2261477/pexels-photo-2261477.jpeg",
        description: "Arms are toast but we made it to the top.",
        tags: ["Indoor", "Active", "Adventurous"],
        likes: 27,
        liked: false,
        seen: false,
    },
    {
        id: 17,
        user: "Liam & Ava",
        avatar: userAvatars["Liam & Ava"],
        time: "3 hours ago",
        title: "Rooftop Dinner",
        image: "https://images.pexels.com/photos/6267/menu-restaurant-vintage-table.jpg",
        description: "City lights and way too much dessert.",
        tags: ["Outdoor", "Expensive", "Romantic"],
        likes: 41,
        liked: false,
        seen: false,
    },
    {
        id: 22,
        user: "Noah & Emma",
        avatar: userAvatars["Noah & Emma"],
        time: "5 hours ago",
        title: "Beach Sunset Walk",
        image: "https://images.pexels.com/photos/1024993/pexels-photo-1024993.jpeg",
        description: "Cold breeze but perfect sunset.",
        tags: ["Outdoor", "Romantic", "Relaxing"],
        likes: 19,
        liked: false,
        seen: false,
    },
    {
        id: 12,
        user: "Jake & Mia",
        avatar: userAvatars["Jake & Mia"],
        time: "1 day ago",
        title: "Mini Golf Showdown",
        image: "https://images.pexels.com/photos/54123/pexels-photo-54123.jpeg",
        description: "Winner gets bragging rights for a week.",
        tags: ["Outdoor", "Cheap", "Active"],
        likes: 33,
        liked: false,
        seen: false,
    },
    {
        id: 30,
        user: "Liam & Ava",
        avatar: userAvatars["Liam & Ava"],
        time: "1 day ago",
        title: "Couples Spa Day",
        image: "https://images.pexels.com/photos/3757957/pexels-photo-3757957.jpeg",
        description: "Most relaxing afternoon we've had in months.",
        tags: ["Indoor", "Expensive", "Relaxing"],
        likes: 46,
        liked: false,
        seen: false,
    },
    {
        id: 6,
        user: "Noah & Emma",
        avatar: userAvatars["Noah & Emma"],
        time: "2 days ago",
        title: "Mountain Trail Hike",
        image: "https://images.pexels.com/photos/1287145/pexels-photo-1287145.jpeg",
        description: "Long climb but unreal views.",
        tags: ["Outdoor", "Active", "Adventurous"],
        likes: 38,
        liked: false,
        seen: false,
    },
    {
        id: 45,
        user: "E&S",
        avatar: userAvatars["E&S"],
        time: "2 days ago",
        title: "Board Game Night",
        image: "https://images.pexels.com/photos/776654/pexels-photo-776654.jpeg",
        description: "Monopoly got intense.",
        tags: ["Indoor", "Cheap", "Relaxing"],
        likes: 22,
        liked: false,
        seen: false,
    },
    {
        id: 19,
        user: "Jake & Mia",
        avatar: userAvatars["Jake & Mia"],
        time: "3 days ago",
        title: "Sushi Night",
        image: "https://images.pexels.com/photos/357756/pexels-photo-357756.jpeg",
        description: "Tried three new rolls and loved them.",
        tags: ["Indoor", "Expensive", "Romantic"],
        likes: 48,
        liked: false,
        seen: false,
    },
    {
        id: 36,
        user: "Noah & Emma",
        avatar: userAvatars["Noah & Emma"],
        time: "1 week ago",
        title: "Campfire Night",
        image: "https://images.pexels.com/photos/1687845/pexels-photo-1687845.jpeg",
        description: "S’mores and stories under the stars.",
        tags: ["Outdoor", "Romantic", "Relaxing"],
        likes: 44,
        liked: false,
        seen: false,
    },
    {
        id: 41,
        user: "E&S",
        avatar: userAvatars["E&S"],
        time: "2 hours ago",
        title: "Ice Cream Downtown",
        image: "https://images.pexels.com/photos/1352278/pexels-photo-1352278.jpeg",
        description: "Tried three flavors each. No regrets.",
        tags: ["Cheap", "Outdoor", "Relaxing"],
        likes: 18,
        liked: false,
        seen: false,
    },
    {
        id: 14,
        user: "Jake & Mia",
        avatar: userAvatars["Jake & Mia"],
        time: "4 hours ago",
        title: "Bowling Rematch",
        image: "https://images.pexels.com/photos/3448246/pexels-photo-3448246.jpeg",
        description: "Loser buys dinner next time.",
        tags: ["Indoor", "Cheap", "Active"],
        likes: 29,
        liked: false,
        seen: false,
    },
    {
        id: 28,
        user: "Liam & Ava",
        avatar: userAvatars["Liam & Ava"],
        time: "6 hours ago",
        title: "Sunset Picnic",
        image: "https://images.pexels.com/photos/1484516/pexels-photo-1484516.jpeg",
        description: "Homemade sandwiches by the lake.",
        tags: ["Outdoor", "Romantic", "Cheap"],
        likes: 37,
        liked: false,
        seen: false,
    },
    {
        id: 5,
        user: "Noah & Emma",
        avatar: userAvatars["Noah & Emma"],
        time: "9 hours ago",
        title: "Aquarium Visit",
        image: "https://images.pexels.com/photos/257596/pexels-photo-257596.jpeg",
        description: "The jellyfish exhibit was unreal.",
        tags: ["Indoor", "Relaxing", "Romantic"],
        likes: 25,
        liked: false,
        seen: false,
    },
    {
        id: 33,
        user: "Jake & Mia",
        avatar: userAvatars["Jake & Mia"],
        time: "1 day ago",
        title: "Escape Room Win",
        image: "https://images.pexels.com/photos/907221/pexels-photo-907221.jpeg",
        description: "Escaped with 2 minutes left!",
        tags: ["Indoor", "Adventurous", "Active"],
        likes: 45,
        liked: false,
        seen: false,
    },
    {
        id: 7,
        user: "E&S",
        avatar: userAvatars["E&S"],
        time: "1 day ago",
        title: "Farmers Market Stroll",
        image: "https://images.pexels.com/photos/2290070/pexels-photo-2290070.jpeg",
        description: "Fresh pastries and local honey.",
        tags: ["Outdoor", "Relaxing", "Cheap"],
        likes: 21,
        liked: false,
        seen: false,
    },
    {
        id: 46,
        user: "Liam & Ava",
        avatar: userAvatars["Liam & Ava"],
        time: "2 days ago",
        title: "Wine Tasting Night",
        image: "https://images.pexels.com/photos/1407846/pexels-photo-1407846.jpeg",
        description: "Found a new favorite red blend.",
        tags: ["Indoor", "Romantic", "Expensive"],
        likes: 50,
        liked: false,
        seen: false,
    },
    {
        id: 11,
        user: "Noah & Emma",
        avatar: userAvatars["Noah & Emma"],
        time: "2 days ago",
        title: "Stargazing Drive",
        image: "https://images.pexels.com/photos/1252890/pexels-photo-1252890.jpeg",
        description: "Drove out of the city for clear skies.",
        tags: ["Outdoor", "Romantic", "Relaxing"],
        likes: 34,
        liked: false,
        seen: false,
    },
    {
        id: 21,
        user: "Jake & Mia",
        avatar: userAvatars["Jake & Mia"],
        time: "3 days ago",
        title: "Cooking Class Together",
        image: "https://images.pexels.com/photos/4252139/pexels-photo-4252139.jpeg",
        description: "Homemade pasta from scratch.",
        tags: ["Indoor", "Active", "Expensive"],
        likes: 39,
        liked: false,
        seen: false,
    },
    {
        id: 48,
        user: "E&S",
        avatar: userAvatars["E&S"],
        time: "3 days ago",
        title: "Arcade Night",
        image: "https://images.pexels.com/photos/1293261/pexels-photo-1293261.jpeg",
        description: "Air hockey rivalry continues.",
        tags: ["Indoor", "Cheap", "Active"],
        likes: 26,
        liked: false,
        seen: false,
    },
    {
        id: 13,
        user: "Liam & Ava",
        avatar: userAvatars["Liam & Ava"],
        time: "4 days ago",
        title: "Kayaking Adventure",
        image: "https://images.pexels.com/photos/2422915/pexels-photo-2422915.jpeg",
        description: "Almost tipped once… almost.",
        tags: ["Outdoor", "Adventurous", "Active"],
        likes: 42,
        liked: false,
        seen: false,
    },
    {
        id: 2,
        user: "Noah & Emma",
        avatar: userAvatars["Noah & Emma"],
        time: "4 days ago",
        title: "Movie Under the Stars",
        image: "https://images.pexels.com/photos/7991579/pexels-photo-7991579.jpeg",
        description: "Blankets, popcorn, projector night.",
        tags: ["Outdoor", "Romantic", "Cheap"],
        likes: 31,
        liked: false,
        seen: false,
    },
    {
        id: 26,
        user: "Jake & Mia",
        avatar: userAvatars["Jake & Mia"],
        time: "5 days ago",
        title: "Morning Hike",
        image: "https://images.pexels.com/photos/674010/pexels-photo-674010.jpeg",
        description: "Early start but worth the view.",
        tags: ["Outdoor", "Active", "Adventurous"],
        likes: 36,
        liked: false,
        seen: false,
    },
    {
        id: 32,
        user: "E&S",
        avatar: userAvatars["E&S"],
        time: "5 days ago",
        title: "Art Museum Visit",
        image: "https://images.pexels.com/photos/20967/pexels-photo.jpg",
        description: "Debated abstract art for 20 minutes.",
        tags: ["Indoor", "Relaxing", "Romantic"],
        likes: 23,
        liked: false,
        seen: false,
    },
    {
        id: 10,
        user: "Liam & Ava",
        avatar: userAvatars["Liam & Ava"],
        time: "6 days ago",
        title: "Fancy Dinner Night",
        image: "https://images.pexels.com/photos/262978/pexels-photo-262978.jpeg",
        description: "Dressed up just because.",
        tags: ["Indoor", "Expensive", "Romantic"],
        likes: 47,
        liked: false,
        seen: false,
    },
    {
        id: 49,
        user: "Noah & Emma",
        avatar: userAvatars["Noah & Emma"],
        time: "6 days ago",
        title: "Bike Ride Downtown",
        image: "https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg",
        description: "Stopped for coffee halfway.",
        tags: ["Outdoor", "Active", "Cheap"],
        likes: 28,
        liked: false,
        seen: false,
    },
    {
        id: 16,
        user: "Jake & Mia",
        avatar: userAvatars["Jake & Mia"],
        time: "1 week ago",
        title: "Beach Volleyball",
        image: "https://images.pexels.com/photos/1263349/pexels-photo-1263349.jpeg",
        description: "Sand everywhere but worth it.",
        tags: ["Outdoor", "Active", "Adventurous"],
        likes: 40,
        liked: false,
        seen: false,
    },
    {
        id: 35,
        user: "E&S",
        avatar: userAvatars["E&S"],
        time: "1 week ago",
        title: "Dessert Cafe Stop",
        image: "https://images.pexels.com/photos/302680/pexels-photo-302680.jpeg",
        description: "Shared cheesecake and coffee.",
        tags: ["Indoor", "Cheap", "Romantic"],
        likes: 24,
        liked: false,
        seen: false,
    },
    {
        id: 20,
        user: "Liam & Ava",
        avatar: userAvatars["Liam & Ava"],
        time: "1 week ago",
        title: "Sunrise Road Trip",
        image: "https://images.pexels.com/photos/21014/pexels-photo.jpg",
        description: "Coffee and open highways.",
        tags: ["Outdoor", "Adventurous", "Romantic"],
        likes: 43,
        liked: false,
        seen: false,
    },
    {
        id: 38,
        user: "Noah & Emma",
        avatar: userAvatars["Noah & Emma"],
        time: "2 weeks ago",
        title: "Park Hammock Date",
        image: "https://images.pexels.com/photos/1029604/pexels-photo-1029604.jpeg",
        description: "Just relaxing in the shade.",
        tags: ["Outdoor", "Relaxing", "Cheap"],
        likes: 30,
        liked: false,
        seen: false,
    }
];
